CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240923000000_Rodonaves') THEN
    CREATE TABLE "Colaboradores" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nome" text NOT NULL,
        "UniCodigo" integer NOT NULL,
        CONSTRAINT "PK_Colaboradores" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240923000000_Rodonaves') THEN
    CREATE TABLE "Unidades" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Codigo" integer NOT NULL,
        "Nome" text NOT NULL,
        "StatusUnidade" boolean NOT NULL,
        CONSTRAINT "PK_Unidades" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240923000000_Rodonaves') THEN
    CREATE TABLE "Usuarios" (
        "UsuarioId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Login" text NOT NULL,
        "Senha" text NOT NULL,
        "Status" boolean NOT NULL,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("UsuarioId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240923000000_Rodonaves') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240923000000_Rodonaves', '8.0.4');
    END IF;
END $EF$;

COMMIT;
