version: "3.5"
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
      - POSTGRES_DB=rodonaves
    ports:
      - "5432:5432"
    volumes:
      - ./db-up.sql:/docker-entrypoint-initdb.d/init-db.sql
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "0.4GB"

networks:
  default:
    driver: bridge
    name: smartcnpj
